# Copyright 2024 William Warner
# SPDX-License-Identifier: GPL-3.0-only
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    python3 \
    python3-dev \
    python3-pip \
    python3-venv \
    python3-launchpadlib && \
    rm -rf /var/lib/apt/lists/*

RUN python3 -m venv /root/.virtualenv
ENV PATH="/root/.virtualenv/bin:$PATH"
RUN pip install pyright

COPY py/.emacs.d .emacs.d
