# Copyright 2024 William Warner
# SPDX-License-Identifier: GPL-3.0-only
ENV DEBIAN_FRONTEND=noninteractive
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
RUN apt-get update && \
    apt-get install -y \
    nodejs && \
    rm -rf /var/lib/apt/lists/*
# the `fetch` mcp is installed with uvx
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH=/root/.local/bin:$PATH
COPY modes/ai/.emacs.d .emacs.d
