# Copyright 2024 William Warner
# SPDX-License-Identifier: GPL-3.0-only
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y \
    clangd \
    bear && \
    rm -rf /var/lib/apt/lists/*
