# Copyright 2024 William Warner
# SPDX-License-Identifier: GPL-3.0-only

COPY --from=golang:1.26-alpine /usr/local/go/ /usr/local/go/
ENV PATH=/root/go/bin:/usr/local/go/bin:$PATH

RUN go install github.com/go-delve/delve/cmd/dlv@latest
RUN go install golang.org/x/tools/gopls@latest
RUN go install mvdan.cc/gofumpt@latest

COPY modes/go/.emacs.d .emacs.d
