# Copyright 2024 William Warner
# SPDX-License-Identifier: GPL-3.0-only
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && apt-get install -y golang && rm -rf /var/lib/apt/lists/*
ENV PATH=/root/go/bin:/usr/local/go/bin:$PATH

RUN go install github.com/go-delve/delve/cmd/dlv@latest
RUN go install golang.org/x/tools/gopls@latest
RUN go install mvdan.cc/gofumpt@latest

COPY modes/go/.emacs.d .emacs.d
