# Copyright 2024 William Warner
# SPDX-License-Identifier: GPL-3.0-only

RUN apk add --no-cache python3 python3-dev py3-pip

RUN python3 -m venv /root/.virtualenv
ENV PATH="/root/.virtualenv/bin:$PATH"
RUN pip install shandy-sqlfmt sqlfluff

COPY modes/sql/.emacs.d .emacs.d
