# Copyright 2024 William Warner
# SPDX-License-Identifier: GPL-3.0-only
ENV DEBIAN_FRONTEND=noninteractive

COPY --from=golang:1.23.5-bookworm /usr/local/go/ /usr/local/go/
ENV PATH=/root/go/bin:/usr/local/go/bin:$PATH

RUN go install github.com/go-delve/delve/cmd/dlv@v1.24.0
RUN go install golang.org/x/tools/gopls@v0.16.2
RUN go install mvdan.cc/gofumpt@v0.7.0

COPY go/.emacs.d .emacs.d
